services:
  db:
    build: ./database 
    container_name: mysql-compose-container
    restart: always
    environment:
      MYSQL_DATABASE: booking_system
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    # volumes:
      # - ./sql_script:/docker-entrypoint-initdb.d

  app:
    build: ./backend 
    container_name: flask-compose-container
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypassword@db/mydatabase
    volumes:
      - ./backend:/app  # Maps your local backend directory to the /app directory in the container

volumes:
  db_data:  # This persists your database between container shutdowns and startups

networks:
  default:  # Defines the default network for the containers to communicate
