services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - ./database/initialise_database.sql:/docker-entrypoint-initdb.d/initialise_database.sql

  flask_backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: mydatabase
    networks:
      - backend-network

networks:
  backend-network: